### PR TITLE
added graph for movie earnings per league

### PR DESCRIPTION
**Pull request by minime283**

### CODE REVIEW

**Comment by t2t2** [comment]
Might want to separate this into an extra page cause it takes up most of the screen on league home page now

**Comment by minime283** [comment]
I can only speak to how we use it but generally the graph is the main attraction, so it would be cool to leave it on the league landing page. One thing I can try doing is shortening the graph, dropping the legend and somehow putting the legend colors in the standings. How does that sound?

**Comment by rkuykendall** [comment]
This is fantastic, @minime283 

Definitely the main attraction of the league page. I also love that it looks like the team colors look like they won't be switching around as the season develops. That made the old graphs confusing sometimes.

Another cool graph might be daily earnings, non-cumulative.

**Comment by rkuykendall** [comment]
As for the visuals, what about the key in the top-left corner? That corner should always be open. Here's an example that puts the key on the graph, as well as showing data on hover which might be nice:

http://www.flotcharts.org/flot/examples/interacting/index.html

**Comment by minime283** [comment]
so regarding the legend specifically, the reason I took it out of the graph is the foundation css was clashing with the chart CSS, and CSS is not my strong suit.

**Pull request merged**
